name: Pre Deployment

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install git-crypt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-crypt

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --import
        shell: bash

      - name: Unlock git-crypt files
        run: git-crypt unlock

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Build
        run: go build -v ./...
